grafana:

  enabled: true

  adminUser: admin

  adminPassword: change-me

  persistence:
    enabled: true
    storageClassName: ebs-gp3
    size: 10Gi

  resources:

    requests:
      cpu: 100m
      memory: 256Mi

    limits:
      cpu: 250m
      memory: 512Mi

  service:
    type: ClusterIP

  ingress:
    enabled: false

  sidecar:

    dashboards:
      enabled: true

      label: grafana_dashboard

      labelValue: "1"

      searchNamespace: ALL

      provider:
        foldersFromFilesStructure