apiVersion: v1

kind: Secret

metadata:

  name: {{ include "multicloud-devsecops.fullname" . }}

  labels:

    {{- include "multicloud-devsecops.labels" . | nindent 4 }}

type: Opaque

stringData:

  DATABASE_USERNAME: {{ .Values.secret.databaseUsername | quote }}

  DATABASE_PASSWORD: {{ .Values.secret.databasePassword | quote }}