apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "application.fullname" . }}
  namespace: {{ .Release.Namespace }}

  labels:
    {{- include "application.labels" . | nindent 4 }}
    project: multicloud-devsecops

spec:

  replicas: {{ .Values.replicaCount }}

  strategy:
    type: RollingUpdate

    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      {{- include "application.selectorLabels" . | nindent 6 }}

  template:

    metadata:

      labels:
        {{- include "application.selectorLabels" . | nindent 8 }}
        project: multicloud-devsecops

    spec:

      containers:

        - name: application

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:

            - name: http
              containerPort: 8080
              protocol: TCP

          envFrom:

            - configMapRef:
                name: {{ .Values.configMap.name }}

            - secretRef:
                name: {{ .Values.secret.name }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}