apiVersion: v1
kind: Secret

metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Release.Namespace }}

  labels:
    {{- include "application.labels" . | nindent 4 }}
    project: multicloud-devsecops

type: Opaque

stringData:

  DATABASE_USERNAME: {{ .Values.secretData.DATABASE_USERNAME | quote }}

  DATABASE_PASSWORD: {{ .Values.secretData.DATABASE_PASSWORD | quote }}