apiVersion: monitoring.coreos.com/v1

kind: PrometheusRule

metadata:

  name: multicloud-devsecops-alerts

  namespace: monitoring

  labels:

    release: kube-prometheus-stack

spec:

  groups:

    - name: kubernetes-alerts

      rules:

        - alert: HighCPUUsage

          expr: >
            100 - (
              avg by(instance)
              (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100
            ) > 80

          for: 5m

          labels:

            severity: warning

          annotations:

            summary: "High CPU usage detected"

            description: "CPU usage has been above 80% for more than 5 minutes."


        - alert: HighMemoryUsage

          expr: >
            (
              1 -
              node_memory_MemAvailable_bytes /
              node_memory_MemTotal_bytes
            ) * 100 > 80

          for: 5m

          labels:

            severity: warning

          annotations:

            summary: "High memory usage detected"

            description: "Memory usage has been above 80% for more than 5 minutes."


        - alert: PodRestartingFrequently

          expr: >
            increase(kube_pod_container_status_restarts_total[15m]) > 3

          for: 5m

          labels:

            severity: warning

          annotations:

            summary: "Pod restarting frequently"

            description: "A Kubernetes pod has restarted more than 3 times in the last 15 minutes."