sonar.projectKey=multicloud-devsecops-platform

sonar.projectName=Multi-Cloud DevSecOps Platform

sonar.projectVersion=1.0

sonar.sources=application/src/main

sonar.tests=application/src/test

sonar.java.binaries=application/target/classes

sonar.sourceEncoding=UTF-8